apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "paldab-loadbalancer.serverMonitorRoleName" . }}
rules:
- apiGroups: [{{ include "paldab-loadbalancer.crdGroup" . }}]
  resources: ["servers"]
  verbs: ["get", "watch", "list", "update"]

