apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "paldab-loadbalancer.serverMonitorRolebindingName" . }}
  namespace: {{ include "paldab-loadbalancer.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "paldab-loadbalancer.serviceAccountName" . }}
  namespace: {{ include "paldab-loadbalancer.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "paldab-loadbalancer.serverMonitorRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
