{{- if .Values.CRDs.install -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ include "paldab-loadbalancer.serverCrdName" . }}
  annotations:
    {{- if .Values.CRDs.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
  labels:
    app: {{ include "paldab-loadbalancer.name" . }}
spec:
  group: {{ include "paldab-loadbalancer.crdGroup" . }}
  names:
    kind: Server
    listKind: ServerList
    plural: servers
    singular: server
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
      - jsonPath: .spec.url
        name: Url
        type: string
      - jsonPath: .spec.healthUrl
        name: HealthUrl
        type: string
      - jsonPath: .spec.isHealthy
        name: IsHealthy
        type: boolean
      name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                healthUrl:
                  type: string
              required:
                - url
          required:
            - spec
      subresources:
        status: {}
{{- end }}
