{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "paldab-loadbalancer.serviceAccountName" . }}
  labels:
    {{- include "paldab-loadbalancer.selectorLabels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
